import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { resolveApiAssetUrl, socialIntelligenceApi } from "../lib/api";
import type { SocialRecord } from "../types/socialIntelligence";

type FeedFilter = { query: string; country: string; platform: string; monitorType: string; brand: string; accountType: string; mediaType: string; dateFrom: string; dateTo: string; sort: string };
type OverviewFilter = { period: string; country: string; platform: string; monitorType: string };
type RankingFilter = { period: string; country: string; metric: "views" | "likes" };
type CloudFilter = { period: string; country: string };
const emptyFeed = (): FeedFilter => ({ query: "", country: "", platform: "", monitorType: "", brand: "", accountType: "", mediaType: "", dateFrom: "", dateTo: "", sort: "recent" });

function periodStart(days: string) { const date = new Date(); date.setUTCDate(date.getUTCDate() - Math.max(0, Number(days) - 1)); return date.toISOString().slice(0, 10); }
function buildParams(values: Record<string, string>, extras: Record<string, string> = {}) { const params = new URLSearchParams(extras); Object.entries(values).forEach(([key, value]) => { if (value && key !== "period" && key !== "metric") params.set(key, value); }); if (values.period) params.set("dateFrom", periodStart(values.period)); return params; }
function number(value: number | null | undefined) { return value == null ? "—" : Intl.NumberFormat("en", { notation: value >= 10000 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value); }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }

function SignalCard({ record, onOpen }: { record: SocialRecord; onOpen: () => void }) {
  return <article className="social-signal-card" onClick={onOpen}>{record.mediaUrl && <div className="social-card-media"><img src={resolveApiAssetUrl(record.mediaUrl)} alt="" loading="lazy" onError={(event) => { event.currentTarget.parentElement!.style.display = "none"; }} /></div>}<div className="social-card-body"><div className="social-badges"><span>{record.country}</span><span className={`platform-${record.platform.toLowerCase()}`}>{record.platform}</span><span className={`monitor-${record.monitorType}`}>{record.monitorType === "trend_discovery" ? "Trend" : "Watchlist"}</span>{record.accountType && <span>{record.accountType}</span>}</div><h3>{record.title}</h3><p>{record.contentSummary || record.content}</p>{record.whyItMatters && <div className="social-why"><b>Why it matters</b>{record.whyItMatters}</div>}<footer><span>{record.accountName || record.brand} · {record.publishedAt ? new Date(record.publishedAt).toLocaleDateString() : "Date unavailable"}</span><span>Views {number(record.views)} · Likes {number(record.likes)}</span></footer></div></article>;
}

export function SocialIntelligenceDashboard() {
  const [overviewFilter, setOverviewFilter] = useState<OverviewFilter>({ period: "7", country: "", platform: "", monitorType: "" });
  const [rankingFilter, setRankingFilter] = useState<RankingFilter>({ period: "7", country: "", metric: "views" });
  const [cloudFilter, setCloudFilter] = useState<CloudFilter>({ period: "7", country: "" });
  const [feedFilter, setFeedFilter] = useState<FeedFilter>(emptyFeed);
  const [selected, setSelected] = useState<SocialRecord | null>(null);
  const filters = useQuery({ queryKey: ["social-intelligence-filters"], queryFn: socialIntelligenceApi.filters });
  const overviewParams = useMemo(() => buildParams(overviewFilter as unknown as Record<string, string>, { limit: "1" }), [overviewFilter]);
  const rankingParams = useMemo(() => buildParams(rankingFilter as unknown as Record<string, string>, { limit: "5", sort: rankingFilter.metric }), [rankingFilter]);
  const cloudParams = useMemo(() => buildParams(cloudFilter as unknown as Record<string, string>, { limit: "1" }), [cloudFilter]);
  const feedParams = useMemo(() => buildParams(feedFilter as unknown as Record<string, string>, { limit: "40", sort: feedFilter.sort }), [feedFilter]);
  const overview = useQuery({ queryKey: ["social-overview", overviewParams.toString()], queryFn: () => socialIntelligenceApi.dashboard(overviewParams) });
  const ranking = useQuery({ queryKey: ["social-ranking", rankingParams.toString()], queryFn: () => socialIntelligenceApi.dashboard(rankingParams) });
  const cloud = useQuery({ queryKey: ["social-cloud", cloudParams.toString()], queryFn: () => socialIntelligenceApi.dashboard(cloudParams) });
  const feed = useQuery({ queryKey: ["social-feed", feedParams.toString()], queryFn: () => socialIntelligenceApi.dashboard(feedParams) });
  const options = filters.data?.options;
  const countries = [{ value: "", label: "All countries" }, ...(options?.countries ?? []).map((value) => ({ value, label: value }))];
  const periods = [{ value: "1", label: "Past 1 day" }, { value: "7", label: "Past 7 days" }, { value: "30", label: "Past 30 days" }];
  const refreshed = feed.data?.meta.cacheGeneratedAt ? new Date(feed.data.meta.cacheGeneratedAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : null;
  const fatal = [overview, ranking, cloud, feed].some((query) => query.isError && !query.data);
  if (fatal) return <div className="error-panel"><p>Social Voice data is temporarily unavailable.</p><button onClick={() => { overview.refetch(); ranking.refetch(); cloud.refetch(); feed.refetch(); }}>Retry</button></div>;
  const updateFeed = (key: keyof FeedFilter, value: string) => setFeedFilter((current) => ({ ...current, [key]: value }));
  const keywords = cloud.data?.keywordCloud ?? [];
  const featuredKeywords = keywords.slice(0, 3);
  const supportingKeywords = keywords.slice(3);
  const maxKeyword = Math.max(1, ...keywords.map((item) => item.count));

  return <div className="social-page">
    <div className="social-page-intro"><div><span>Social Voice</span><h1>Market signals and brand activity</h1></div><p>{feed.data?.meta.stale ? "Using local pipeline snapshot" : "Google Sheet synced"}{refreshed ? ` · ${refreshed}` : ""}</p></div>
    <section className="social-overview-module"><header><div><span>Market overview</span><strong>Signals and engagement</strong></div><div className="social-mini-filters"><Select label="Period" value={overviewFilter.period} onChange={(period) => setOverviewFilter({ ...overviewFilter, period })} options={periods} /><Select label="Country" value={overviewFilter.country} onChange={(country) => setOverviewFilter({ ...overviewFilter, country })} options={countries} /><Select label="Platform" value={overviewFilter.platform} onChange={(platform) => setOverviewFilter({ ...overviewFilter, platform })} options={[{ value: "", label: "All platforms" }, ...(options?.platforms ?? []).map((value) => ({ value, label: value }))]} /><Select label="Monitor" value={overviewFilter.monitorType} onChange={(monitorType) => setOverviewFilter({ ...overviewFilter, monitorType })} options={[{ value: "", label: "All sources" }, ...(options?.monitorTypes ?? []).map((value) => ({ value, label: value === "trend_discovery" ? "Trend" : "Watchlist" }))]} /></div></header><div className="social-summary-strip"><div><span>Signals</span><strong>{number(overview.data?.metrics.signalCount)}</strong></div><div><span>Views</span><strong>{number(overview.data?.metrics.totalViews)}</strong></div><div><span>Likes</span><strong>{number(overview.data?.metrics.totalLikes)}</strong></div><div><span>Trend share</span><strong>{overview.data ? `${Math.round(overview.data.metrics.trendShare * 100)}%` : "—"}</strong></div></div></section>
    <section className="social-discovery-grid">
      <article className="social-ranking-module"><header><div><span>Top ranking</span><h2>Most popular content</h2></div><div className="social-inline-controls"><select value={rankingFilter.period} onChange={(e) => setRankingFilter({ ...rankingFilter, period: e.target.value })}>{periods.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={rankingFilter.country} onChange={(e) => setRankingFilter({ ...rankingFilter, country: e.target.value })}>{countries.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={rankingFilter.metric} onChange={(e) => setRankingFilter({ ...rankingFilter, metric: e.target.value as "views" | "likes" })}><option value="views">By views</option><option value="likes">By likes</option></select></div></header><div className="social-ranking-list">{ranking.data?.records.map((record, index) => <button key={record.recordId} onClick={() => setSelected(record)}><b>{index + 1}</b>{record.mediaUrl ? <img src={resolveApiAssetUrl(record.mediaUrl)} alt="" /> : <i>{record.platform}</i>}<span><strong>{record.title}</strong><small>{record.country} · {record.platform} · {record.accountName}</small></span><em>{rankingFilter.metric === "views" ? number(record.views) : number(record.likes)}<small>{rankingFilter.metric}</small></em></button>)}</div></article>
      <article className="social-cloud-module"><header><div><span>Hot topics</span><h2>What the market is talking about</h2></div><div className="social-inline-controls"><select value={cloudFilter.period} onChange={(e) => setCloudFilter({ ...cloudFilter, period: e.target.value })}>{periods.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={cloudFilter.country} onChange={(e) => setCloudFilter({ ...cloudFilter, country: e.target.value })}>{countries.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div></header><div className="social-topic-leaders">{featuredKeywords.map((item, index) => <div key={item.label}><small>#{index + 1} theme</small><strong>{item.label}</strong><span>{item.count} signals</span></div>)}</div><div className="social-word-cloud">{supportingKeywords.map((item, index) => <span key={item.label} className={`word-tone-${index % 5}`} style={{ fontSize: `${11 + (item.count / maxKeyword) * 11}px` }} title={`${item.count} signals`}>{item.label}<i>{item.count}</i></span>)}</div>{!keywords.length && <p className="empty">No discussion themes found for this period.</p>}</article>
    </section>
    <section className="social-feed-module"><header><div><span>Latest intelligence</span><h2>Verified content feed</h2><small>{feed.data?.meta.filteredCount ?? 0} matching records</small></div><button className="social-reset" onClick={() => setFeedFilter(emptyFeed())}>Reset filters</button></header><div className="social-filter-grid"><label className="social-search">Search<input value={feedFilter.query} onChange={(e) => updateFeed("query", e.target.value)} placeholder="Title, content or account" /></label>{([ ["monitorType", "Monitor type", options?.monitorTypes], ["country", "Country", options?.countries], ["brand", "Brand", options?.brands], ["platform", "Platform", options?.platforms], ["accountType", "Account type", options?.accountTypes], ["mediaType", "Media type", options?.mediaTypes] ] as [keyof FeedFilter, string, string[] | undefined][]).map(([key, label, items]) => <label key={key}>{label}<select value={feedFilter[key]} onChange={(e) => updateFeed(key, e.target.value)}><option value="">All</option>{items?.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>)}<label>From<input type="date" value={feedFilter.dateFrom} min={options?.dateRange.min ?? undefined} max={options?.dateRange.max ?? undefined} onChange={(e) => updateFeed("dateFrom", e.target.value)} /></label><label>To<input type="date" value={feedFilter.dateTo} min={options?.dateRange.min ?? undefined} max={options?.dateRange.max ?? undefined} onChange={(e) => updateFeed("dateTo", e.target.value)} /></label><label>Sort<select value={feedFilter.sort} onChange={(e) => updateFeed("sort", e.target.value)}><option value="recent">Most recent</option><option value="views">Most viewed</option><option value="likes">Most liked</option></select></label></div>{feed.isLoading ? <div className="module-loading">Loading intelligence…</div> : <div className="social-signal-grid">{feed.data?.records.map((record) => <SignalCard key={record.recordId} record={record} onOpen={() => setSelected(record)} />)}</div>}{!feed.isLoading && !feed.data?.records.length && <p className="empty">No intelligence matches the selected filters.</p>}</section>
    {selected && <div className="social-drawer-backdrop" onClick={() => setSelected(null)}><aside className="social-drawer" onClick={(event) => event.stopPropagation()}><button onClick={() => setSelected(null)}>×</button>{selected.mediaUrl && <img src={resolveApiAssetUrl(selected.mediaUrl)} alt="" />}<div className="social-badges"><span>{selected.country}</span><span>{selected.platform}</span><span>{selected.monitorType}</span></div><h2>{selected.title}</h2><p className="social-full-content">{selected.content}</p><h3>Why it matters</h3><p>{selected.whyItMatters}</p><div className="social-impact-list">{selected.businessImpact.map((item) => <span key={item}>{item}</span>)}</div><a href={selected.sourceUrl} target="_blank" rel="noreferrer">Open original post ↗</a></aside></div>}
  </div>;
}
